// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqplzjhsasxyapnthxnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxcGx6amhzYXN4eWFwbnRoeG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzY4ODcsImV4cCI6MjA3Mzg1Mjg4N30.YXNm7pu16A7NAB6TC3KMvYKTtKOI9ikxby3RpMrfY9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});